name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
# branches: [main]
# https://github.com/actions/setup-java
jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest # use fixed version
      steps:
        # - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        # - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        # - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        # - name: Check out repository code
          uses: actions/checkout@v4 # public actions
        # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
        # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

        - name: List files in the repository
        - run: | # Pipe for multiple lines, better: shell files instead of multiple lines
              ls ${{ github.workspace }}
              steps:
        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
        - run: |
            jave -version

            # - run: echo "ğŸ This job's status is ${{ job.status }}.